{
    "title": "What's 'fs:[0]' doing and how can I execute it step by step?",
    "link": "https://reverseengineering.stackexchange.com/questions/1911/whats-fs0-doing-and-how-can-i-execute-it-step-by-step",
    "content": "<div class=\"s-prose js-post-body\" itemprop=\"text\">\n<p>In a 32 bits Windows binary, I see this code:</p>\n<pre><code>    push next\n    push fs:[0]\n    mov fs:[0], esp\n    int3\n    ...\nnext:\n</code></pre>\n<p>I see that something happens on the <code>int3</code> (an error), but I don't understand why, and how to follow execution while keeping control.</p>\n</div>",
    "votes": "24",
    "answers": 1,
    "views": "13k",
    "tags": [
        "windows",
        "x86",
        "seh"
    ],
    "user": "Ange",
    "time": "Apr 23, 2013 at 12:31",
    "comments": [
        {
            "user": "Ange",
            "text": "<span class=\"comment-copy\"><a href=\"https://www.dropbox.com/s/3oj74p0wz1x1zkq/Exceptions.zip\" rel=\"nofollow noreferrer\">SEH PoCs</a></span>",
            "time": null
        }
    ],
    "answers_data": [
        {
            "content": "<div class=\"s-prose js-post-body\" itemprop=\"text\">\n<h1>TL;DR</h1>\n<ol>\n<li><p>the first 3 lines set an exception handler (an 'error catcher')</p></li>\n<li><p>the <code>int3</code> generates an exception</p></li>\n<li><p>execution resumes at <code>next</code></p></li>\n</ol>\n<hr/>\n<h1>Explanation</h1>\n<p>this trick is (ab)using <a href=\"http://www.microsoft.com/msj/0197/exception/exception.aspx\" rel=\"noreferrer\">Structured Exception Handling</a>, a mechanism to define exception handlers, typically by compilers when <code>try</code>/<code>catch</code> blocks are used.</p>\n<p>In 32bits versions of Windows, they can be set on the fly, without any pre-requirement (unless the binary is compiled with /SafeSEH).</p>\n<p>The first element of the exception handlers' chain is pointed by the first member of the <a href=\"http://en.wikipedia.org/wiki/Win32_Thread_Information_Block\" rel=\"noreferrer\">Thread Information Block (TIB)</a>, in turn a member of the <a href=\"http://undocumented.ntinternals.net/UserMode/Undocumented%20Functions/NT%20Objects/Thread/TEB.html\" rel=\"noreferrer\">Thread Environment Block (TEB)</a>, which is pointed to by <code>fs:0</code> (which is also reachable 'directly' - via something like <code>ds:7efdd00</code>, depending on the OS version etc)</p>\n<p>So here is what happens:</p>\n<ol>\n<li><p>the first two <code>push</code> reserve stack space for the structure <code>_EXCEPTION_REGISTRATION_RECORD</code>.</p>\n<ol>\n<li>the new top handler</li>\n<li>the previous top handler, which was until now at <code>fs:[0]</code></li>\n</ol></li>\n<li><p>the <code>mov</code> sets the current stack position as the new structure. When an exception happens, <code>next</code> will be now the first called handler.</p></li>\n<li><p><code>int3</code> triggers an exception instantaneously (there are many other kinds of <a href=\"http://seh.corkami.com\" rel=\"noreferrer\">exception triggers</a>).</p></li>\n<li><p>as an exception is triggered, Windows dispatches the exception to the first handler, and the next one if it's not handled, until one of them has handled it.</p></li>\n</ol>\n<p><img alt=\"flowchart of Exception handling\" src=\"https://raw.githubusercontent.com/angea/wiki_old/master/pics/seh_flowchart.png\"/></p>\n<h1>Following execution</h1>\n<p>This is done here under OllyDbg 1.10. YMMV.</p>\n<p>As we want to go through exceptions ourselves, we have to ask OllyDbg not to handle them:</p>\n<ol>\n<li><p>go to debugging options: <kbd>Alt</kbd>-<kbd>O</kbd>, tab <code>Exceptions</code></p></li>\n<li><p>unselect <code>INT3 breaks</code></p></li>\n</ol>\n<p>And when an exception is triggered, we have to enforce that execution is done via exceptions (see below).</p>\n<p>Here are 3 methods of increasing level to follow the exception handling execution safely:</p>\n<h2>step by step: set a breakpoint manually</h2>\n<p>As the handler has just been set on the stack, you can manually set a breakpoint then run.</p>\n<ol>\n<li><p>select the new handler address on the stack</p>\n<p><img alt=\"new handler on the stack\" src=\"https://i.sstatic.net/QQQOQ.png\"/></p></li>\n<li><p>Right-click or <kbd>F10</kbd></p>\n<ul>\n<li>select <code>Follow in Dump</code></li>\n</ul></li>\n<li><p>in the dump window, open the menu (same shortcut)</p>\n<ul>\n<li>select <code>BreakPoint</code>, then <code>Hardware, on execution</code></li>\n</ul></li>\n<li><p>Execute: menu <code>Debug/Run</code> / shortcut <kbd>F9</kbd> / command-line <code>g</code></p></li>\n<li><p>Exceptions will be triggered</p></li>\n<li><p>Execute with exception handling: shortcut <kbd>Shift</kbd>-<kbd>F9</kbd> / command-line <code>ge</code>.</p></li>\n</ol>\n<h2>shortcut: execute until exception handler via command-line</h2>\n<ul>\n<li><p>as the address is on the stack, the easiest way is to type via the command line <code>ge [esp+4]</code>, which means, <code>Go with Exceptions</code>, until the 2nd address on the stack is encountered. Thus, no need to set and unset a breakpoint.</p>\n<ul>\n<li>in the case of a more complex example, where the address might not be obvious on the stack anymore, then the absolute formula would be <code>ge ds:[fs:[0]+4]</code>, which just gets the actual address from the TIB.</li>\n</ul></li>\n</ul>\n<h2>keeping full control: break on <code>KiUserExceptionDispatcher</code></h2>\n<p><code>KiUserExceptionDispatcher</code> is the Windows API handling all user-mode exceptions. Setting a breakpoint there guarantees that you keep full control - but then, you're in the middle of a Windows API ;) </p>\n<p>In this case, you can ask OllyDbg to skip exceptions, as you will still break execution manually in any cases. You might also want to combine that with a <a href=\"http://tuts4you.com/download.php?list.53\" rel=\"noreferrer\">script</a>.</p>\n<p>Of course, some advanced code might check that you set a breakpoint on it before triggering an exception.</p>\n</div>",
            "votes": "38",
            "user": "Gehock",
            "time": "Apr 26, 2020 at 18:00",
            "is_accepted": true,
            "comments": [
                {
                    "user": "newgre",
                    "text": "<span class=\"comment-copy\">\"In 32bits versions of Windows, they can be set on the fly, without any pre-requirement.\" That's not quite correct, it depends on how the executable was compiled, e.g., if compiled with SafeSEH ntdll!RtlDispatchException (IIRC) will terminate your process if you registered an SEH handler on the fly.</span>",
                    "time": null
                },
                {
                    "user": "newgre",
                    "text": "<span class=\"comment-copy\">Also, a pretty common obfuscation technique is to modify the instruction pointer of the CPU context that is passed to the SEH handler. So it's usually a good idea to place a breakpoint before the call to NtContinue inside KiUserExceptionDispatcher. IDAStealth can do this for you automatically btw.</span>",
                    "time": null
                },
                {
                    "user": "newgre",
                    "text": "<span class=\"comment-copy\">Execution <i>does</i> resume at next and since the OS doesn't force you to return from the exception handler, that statement is technically correct. In fact, that's exactly how C++ exceptions are implemented in the CRT.</span>",
                    "time": null
                },
                {
                    "user": "peter ferrie",
                    "text": "<span class=\"comment-copy\">don't forget that any Vectored Exception Handler which was registered already will receive control first.  The SEH might never execute at all.</span>",
                    "time": null
                },
                {
                    "user": "mrduclaw",
                    "text": "<span class=\"comment-copy\">This is a really great write-up, I'd love to see SEHOP added to this sometime for the sake of completeness.  Also, just to be extremely nit-picky: when <code>int3</code> fires, an interrupt does occur and an interrupt handler invoked, right?  I understand that stepping through the kernel call would be impossible in ImmunityDebugger (and while kernel debugging with Windbg, IIRC), but I just wanted to clarify for my own understanding.</span>",
                    "time": null
                }
            ]
        }
    ]
}