{
    "title": "Hooking in Immunity - LogBpHook not working",
    "link": "https://reverseengineering.stackexchange.com/questions/12854/hooking-in-immunity-logbphook-not-working",
    "content": "I try to use a simple hook on different memory allocation functions in Immunity. But the hook doesn't react at all (no logging).\nFirst of all my hook class:\n<pre><code>class AllocHook(LogBpHook):\n    def __init__(self):\n        LogBpHook.__init__(self)\n\n    def run(self, regs):\n        imm = immlib.Debugger()\n        imm.log(\"     ++++++++++++++++++ HOOOKED\")\n        imm.log(str(regs))\n        imm.log(\"     ++++++++++++++++++ HOOOKED\")\n</code></pre>\nThe function to init and add the hook.\n<pre><code>def hookAlloc(imm):\n    global vAllocHo\n    # Retrieve address of Allocs\n    # Create hook object and add hook\n    va1 = imm.getAddress(\"kernel32.LocalAlloc\")\n    vAllocHo = AllocHook()\n    vAllocHo.add(\"va alloc\",va1)\n    vAllocHo.enable()\n</code></pre>\nSo the <pre><code>log</code></pre> appears in the breakpoint window, but the <pre><code>run()</code></pre> function actually never gets called. \n<pre><code>Breakpoints, item 26\nAddress=76C91668 kernel32.LocalAlloc\nModule=kernel32\nActive=Log\nDisassembly=MOV EDI,EDI\n</code></pre>\nThe log messages of the breakpoints are at least disappearing when the hook is activated. For example, after activating the hook, the following logging messages are not displayed anymore:\n<pre><code>Log data, item 40\nAddress=76C91668 \nMessage=[19:12:51] Breakpoint at kernel32.LocalAlloc\n</code></pre>\nAre there special settings in the options left, which I have to consider first?\n",
    "votes": "2",
    "answers": 1,
    "views": "353",
    "tags": [
        "debugging",
        "immunity-debugger",
        "function-hooking"
    ],
    "user": "knx",
    "time": "Jun 15, 2016 at 17:25",
    "comments": [],
    "answers_data": [
        {
            "content": "In the heat of the moment I didn't start Immunity as an Administrator.\nSo missing privileges have caused this behaviour during the debugging process.\n",
            "votes": "1",
            "user": "knx",
            "time": "Jun 15, 2016 at 18:15",
            "is_accepted": true,
            "comments": []
        }
    ]
}